[discord]
# 大獎、看門狗重啟、水道異常告警頻道
alert_webhook = https://discord.com/api/webhooks/1488034531888992266/hVB1hrg4FSqAokSVonelRUj_8Q9253K8aYCI-w7OyvwKYr-j2suwdEVYY-cZes12HtbO
# 每 30 分鐘收益與日預估報表頻道
report_webhook = https://discord.com/api/webhooks/1488032921636835418/ME_fQrilVYMjB3Sp-dbgYzF93MXDh2avxvnf_tSVYCglOmaOpcM5cK2ITqL4PzLThjcB

[custom_stats]
# 格式：英文原名 #中文標籤 (程式會自動偵測英文並顯示中文)
item1 = Seven Years Bad Luck #七年
item2 = Nightmare Map #夢魘圖
item3 = The Black Scythe #漆黑幣

[settings]
# 是否關閉水道告警推播 (true: 不推播 / false: 滿5次即告警)
aqueduct_only = false